# Generated by Django 3.2.16 on 2022-11-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_title_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание произведения'),
        ),
    ]
